
import java.awt.Frame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;


public class MainMenu extends javax.swing.JFrame {
    private static boolean loggedIn = false;

    public static boolean isLoggedIn() {
        return loggedIn;
    }

    public static void setLoggedIn(boolean loggedIn) {
        MainMenu.loggedIn = loggedIn;
    }
    
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        setExtendedState(Frame.MAXIMIZED_BOTH);
        initState(loggedIn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        subLogin = new javax.swing.JMenuItem();
        subLogout = new javax.swing.JMenuItem();
        subExit = new javax.swing.JMenuItem();
        menuMaster = new javax.swing.JMenu();
        subBarang = new javax.swing.JMenuItem();
        subSuplier = new javax.swing.JMenuItem();
        subPelanggan = new javax.swing.JMenuItem();
        subAkun = new javax.swing.JMenuItem();
        menuTransaksi = new javax.swing.JMenu();
        subPembelian = new javax.swing.JMenuItem();
        subPenjualan = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 51));

        menuFile.setText("File");

        subLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        subLogin.setText("Login");
        subLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subLoginActionPerformed(evt);
            }
        });
        menuFile.add(subLogin);

        subLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        subLogout.setText("Logout");
        subLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subLogoutActionPerformed(evt);
            }
        });
        menuFile.add(subLogout);

        subExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        subExit.setText("Exit");
        subExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subExitActionPerformed(evt);
            }
        });
        menuFile.add(subExit);

        jMenuBar1.add(menuFile);

        menuMaster.setText("Master");

        subBarang.setText("Barang");
        subBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subBarangActionPerformed(evt);
            }
        });
        menuMaster.add(subBarang);

        subSuplier.setText("Suplier");
        subSuplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subSuplierActionPerformed(evt);
            }
        });
        menuMaster.add(subSuplier);

        subPelanggan.setText("Pelanggan");
        subPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subPelangganActionPerformed(evt);
            }
        });
        menuMaster.add(subPelanggan);

        subAkun.setText("Akun");
        subAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subAkunActionPerformed(evt);
            }
        });
        menuMaster.add(subAkun);

        jMenuBar1.add(menuMaster);

        menuTransaksi.setText("Transaksi");

        subPembelian.setText("Pembelian");
        menuTransaksi.add(subPembelian);

        subPenjualan.setText("Penjualan");
        subPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subPenjualanActionPerformed(evt);
            }
        });
        menuTransaksi.add(subPenjualan);

        jMenuBar1.add(menuTransaksi);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 363, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subExitActionPerformed
        int jawaban = JOptionPane.showConfirmDialog(
                this,
                "anda yakin ingin keluar program ?");
        if (jawaban==0){
            System.exit(0);
        
        }
        
    }//GEN-LAST:event_subExitActionPerformed

    private void subAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subAkunActionPerformed
    MasterAkun masterAkun = new MasterAkun(this, true);
   masterAkun.setVisible(true);
    }//GEN-LAST:event_subAkunActionPerformed

    private void subPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subPenjualanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subPenjualanActionPerformed

    private void subSuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subSuplierActionPerformed
    MasterSuplier masterSuplier = new MasterSuplier(this, true);
   masterSuplier.setVisible(true);
    }//GEN-LAST:event_subSuplierActionPerformed

    private void subLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subLoginActionPerformed
    LoginForm loginForm = new LoginForm(this, true);
    loginForm.setVisible(true);
        initState(loggedIn);
    }//GEN-LAST:event_subLoginActionPerformed

    private void subLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subLogoutActionPerformed
   
        
    }//GEN-LAST:event_subLogoutActionPerformed

    private void subBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subBarangActionPerformed
    MasterBarang masterBarang = new MasterBarang(this, true);
    masterBarang.setVisible(true);
    }//GEN-LAST:event_subBarangActionPerformed

    private void subPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subPelangganActionPerformed
    MasterPelanggan masterPelanggan = new MasterPelanggan(this, true);
    masterPelanggan.setVisible(true);
    }//GEN-LAST:event_subPelangganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuMaster;
    private javax.swing.JMenu menuTransaksi;
    private javax.swing.JMenuItem subAkun;
    private javax.swing.JMenuItem subBarang;
    private javax.swing.JMenuItem subExit;
    private javax.swing.JMenuItem subLogin;
    private javax.swing.JMenuItem subLogout;
    private javax.swing.JMenuItem subPelanggan;
    private javax.swing.JMenuItem subPembelian;
    private javax.swing.JMenuItem subPenjualan;
    private javax.swing.JMenuItem subSuplier;
    // End of variables declaration//GEN-END:variables
   
  
    private void initState(boolean b) {
    new SwingUtil(). enableMenus(b,
            subBarang,
            subLogout,
            subAkun,
            subSuplier,
            subPembelian,
            subPelanggan,
            subPenjualan);    
    }

}
class SwingUtil{
    public void enableMenus(boolean active,
            JMenuItem...items) {
        for (JMenuItem item : items ){
            item.setEnabled(active);
        }
    }
}

